keys:
  - &users:
    - &mar age1sv7v502vtcfqy3qpgp8jvk92rcajwgsqzngldt4233h4966jmvnq2lre7f
  - &hosts:
    - &zangetsu: age1st5c42z0nrx4gvh3r52e73e9vyx8ultu0zwrf38ltnsvj24l03nsglfh74
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *mar
        - *zangetsu
