keys:
  - &users:
    - &mar age1sv7v502vtcfqy3qpgp8jvk92rcajwgsqzngldt4233h4966jmvnq2lre7f
  - &hosts:
    - &zangetsu-old age1st5c42z0nrx4gvh3r52e73e9vyx8ultu0zwrf38ltnsvj24l03nsglfh74
    - &zangetsu age1q3hvkkv9rpyr6qr0lq0yzw9pmxcdem3xw7azvgvl7u8mdt0hs5jschmtt6
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *mar
        - *zangetsu-old
        - *zangetsu
