keys:
  - &users:
    - &mirza age1sv7v502vtcfqy3qpgp8jvk92rcajwgsqzngldt4233h4966jmvnq2lre7f
    - &mar age13v3rsufntuytj602vserdgxpggqs6zpklp78gc58kdznxaza83fsederp0
    - &mar-ultron age13k0fcuy48gagkclfmu5d27rt7jr3q7vk5lrttvjjmaftg0cx6evqehxqet
  - &hosts:
    - &isshin age103v0t5udfzraudqvjtnk6ted9qg6t38qjx2knyq99c5hg70894csd0hw84
    - &zangetsu age1st5c42z0nrx4gvh3r52e73e9vyx8ultu0zwrf38ltnsvj24l03nsglfh74
    - &yhwach age1t9f9ud76j9jhtj68g6cse0qtcw79sf3xf0p8u03s897ytk33hpgqga2lp9
    - &sado age1skw9g0546wm60qsammr42cvhakmpp9cyf86r8f6t2ywlh0u223rqqzzqhk
    - &kuchiki age1zgg9evn6xq8hug3angmdewdhm3gqlrrwl7uss3326zfypalmmdwq2pcuht
    - &lil-nas-x age1j8lcp9mwvxt5hqn0s5nxganc3f2ry5zp8t6yr0mewf2mlpzhr42sqz575d
    - &shinji age1z5skf37r5sk337mj0enfggk7x06u0mp3c403x75mn2746l8kxqus2uy7kv
    - &yoruichi age1v735safn23adh2rwqk2stz67erj0l4n423rz66aldhntv4pxd48sxwt67a
    - &kenpachi age163yahwzp9086xhrrga0euq88pfhv5x47zpjtk6zd64jl2c2mhgfsfuweg2
    - &aizen age1x9zwdpgstwrkhn0agf7gcwdu9ehk8sxd58fwls87jyfx78efvexq2z609u
    - &madara age1uwhwtaxyk9926w3wsgjpgxxzd786vmggxq5wmt4m4nzhaj2macfqkn3gje
    - &kyuubi age135vshf3jd0elrxfdl5zzjd4hsnk8n3q8uxe2updd5c7w8xzgvvns4et26u
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *mirza
          - *mar
          - *mar-ultron
          - *isshin
          - *zangetsu
          - *yhwach
          - *sado
          - *kuchiki
          - *lil-nas-x
          - *shinji
          - *yoruichi
          - *kenpachi
          - *aizen
          - *madara
          - *kyuubi
